field: e1f04add-99dc-4c26-ba6b-9aa9d53775bb # Inhalt
fieldLayouts:
  96247d08-1d7b-408c-b14f-6912aaa31687:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a53e37b7-7d3a-4c27-98d6-7a074ff615ad # Formular
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96362da1-a90d-497c-a385-0d7c7678f110
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fd7129cd-d064-4a57-aa35-dae7182f1338
        userCondition: null
fields:
  a53e37b7-7d3a-4c27-98d6-7a074ff615ad: # Formular
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: form
    instructions: null
    name: Formular
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      selectionLabel: 'Formular auswählen'
      showSiteMenu: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
handle: form
name: Formular
sortOrder: 8
