columnSuffix: null
contentColumnType: string
fieldGroup: 1174c6d2-258f-4569-8dc3-77d5158f847d # Settings
handle: contactForm
instructions: null
name: Kontaktformular
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Formular auswählen'
  showSiteMenu: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: verbb\formie\fields\Forms
