columnSuffix: null
contentColumnType: string
fieldGroup: 1174c6d2-258f-4569-8dc3-77d5158f847d # Settings
handle: mainNavigation
instructions: null
name: Hauptnavigation
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: false
  sources:
    - singles
    - 'section:40bbfc69-d990-4bff-b2a0-195c12380074' # Seiten
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
