defaultPlacement: end
enableVersioning: true
handle: home
name: Startseite
previewTargets:
  -
    __assoc__:
      -
        - label
        - Default
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  95121e66-126c-4507-ab4c-5b40c8aafa82: # b-aware Kollektiv
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
  b0c5c514-091f-4684-8b80-874d45688d19: # b-aware Kollektiv EN
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
