handle: default
name: 'b-aware Default'
outputCssLayout: true
outputCssLocation: page-header
outputCssTheme: true
outputJsBase: true
outputJsLocation: page-footer
outputJsTheme: true
sortOrder: null
template: _forms
useCustomTemplates: true
